import { Mitr } from 'next/font/google'
import { ThemeProvider } from './contexts/ThemeContext'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import './globals.css'

const mitr = Mitr({ subsets: ['latin'], weight: '400' })


export const metadata = {
  title: 'Medical App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mitr.className} min-h-screen flex flex-col overflow-x-hidden `}>
          <ThemeProvider>
            <Navbar />
            <ToastContainer />
            <div className='flex-grow overflow-auto'>
              {children}
            </div>
            <Footer />
          </ThemeProvider>
      </body>
    </html>
  )
}